Repository uwreact/frc_control, pull requests merged in 2019-03, with the labels that each got.

#41 Update C++03 packages to C++14
  analog_state_controller/include/analog_state_controller/analog_command_interface.h
  analog_state_controller/include/analog_state_controller/analog_state_interface.h
  binary_state_controller/include/binary_state_controller/binary_command_interface.h
  binary_state_controller/include/binary_state_controller/binary_state_interface.h
  frc_robot_hw/src/frc_robot_hw.cpp
  frc_robot_hw/src/frc_robot_hw_real.cpp
  frc_robot_hw/src/robot_base_node.cpp
  frc_robot_hw/src/robot_control_loop.cpp
  frc_robot_sim/CMakeLists.txt
  frc_robot_sim/src/gazebo_hw_plugin.cpp
  pdp_state_controller/include/pdp_state_controller/pdp_state_controller.h
  pdp_state_controller/include/pdp_state_controller/pdp_state_interface.h
  pdp_state_controller/src/pdp_state_controller.cpp
  ternary_state_controller/include/ternary_state_controller/ternary_command_interface.h
  ternary_state_controller/include/ternary_state_controller/ternary_state_interface.h
Labels: 🚀 feature

#44 Fix unsource_ros script
  installation/INSTALLATION.md
  installation/unsource_ros.bash
Labels: :bug: bug

#42 Add clang-tidy
  .clang-tidy
  frc_robot_hw/include/frc_robot_hw/frc_robot_hw.h
  frc_robot_hw/src/frc_robot_hw.cpp
  frc_robot_sim/include/frc_robot_sim/gazebo_hw_plugin.h
  frc_robot_sim/src/frc_robot_hw_sim.cpp
  frc_robot_sim/src/gazebo_hw_plugin.cpp
  run_clang_tidy.py
  setup_catkin.bash
Labels: 🚀 feature

#45 Prefer else on same line as closing brace
  .clang-format
  frc_robot_hw/src/frc_robot_hw.cpp
  frc_robot_hw/src/robot_base_node.cpp
  frc_robot_sim/src/gazebo_hw_plugin.cpp
Labels: 🚀 feature

#46 Add yapf and pylint configs
  .pylintrc
  .style.yapf
  README.md
  extract_archives.py
  installation/install_3rd_party_libs.py
  run_clang_tidy.py
  setup_catkin.bash
Labels: 🚀 feature

#47 Add driver_station
  .gitignore
  driver_station/CMakeLists.txt
  driver_station/package.xml
  driver_station/scripts/driver_station
  driver_station/setup.py
  driver_station/src/driver_station/__init__.py
  driver_station/src/driver_station/window.py
  frc_control/package.xml
Labels: 🚀 feature

#55 Add default labels to issue templates
  .github/ISSUE_TEMPLATE/1_BUG_REPORT.md
  .github/ISSUE_TEMPLATE/2_FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/3_DOCUMENTATION_ERROR.md
  .github/ISSUE_TEMPLATE/4_QUESTION.md
  .github/ISSUE_TEMPLATE/5_META_ISSUE.md
Labels: 📖 documentation

#56 Driver Station/FMS Messages
  frc_control/package.xml
  frc_msgs/CMakeLists.txt
  frc_msgs/msg/CANStatus.msg
  frc_msgs/msg/DriverStationMode.msg
  frc_msgs/msg/JoyArray.msg
  frc_msgs/msg/JoyFeedback.msg
  frc_msgs/msg/MatchData.msg
  frc_msgs/msg/MatchTime.msg
  frc_msgs/msg/RobotState.msg
  frc_msgs/package.xml
  frc_robot_hw/CMakeLists.txt
  frc_robot_hw/include/frc_robot_hw/frc_robot_hw_real.h
  frc_robot_hw/package.xml
  frc_robot_hw/src/frc_robot_hw_real.cpp
Labels: 🚀 feature

#59 CI style checks
  .clang-tidy
  .pylintrc
  .travis.yml
  driver_station/package.xml
  driver_station/scripts/driver_station
  driver_station/src/driver_station/window.py
  frc_msgs/CMakeLists.txt
  frc_msgs/package.xml
  frc_robot_hw/CMakeLists.txt
  frc_robot_sim/CMakeLists.txt
  installation/install_3rd_party_libs.py
  run_clang_tidy.py
  run_linters.py
Labels: 🚀 feature

#60 Linter bugfixes
  .travis.yml
  run_linters.py
Labels: 🚀 feature
